services:
  app:
    image: ${DOCKERHUB_USERNAME}/docker-vps-deploy:${IMAGE_TAG}
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DB_URL=postgresql://postgres:MyPassword123@91.99.3.185:5432/todos
      # - DB_URL=${DB_URL}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:17-alpine
    restart: always
    user: postgres
    shm_size: 256mb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyPassword123
      POSTGRES_PORT: 5432
      # POSTGRES_DB: ${DB_NAME}
      # POSTGRES_USER: ${DB_USER}
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_PORT: ${DB_PORT}
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
