name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-vps-deploy:latest, ${{ secrets.DOCKERHUB_USERNAME }}/docker-vps-deploy:${{ github.sha }}

  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Create Docker context
        run: |
          docker context create vps-context --docker "host=ssh://${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}"
          docker context use vps-context

      - name: Deploy to VPS with docker compose
        run: |
          # Create .env file with all required variables
          cat > .env << EOF
          # Database secrets (from GitHub secrets)
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_URL=${{ secrets.DB_URL }}

          # Configuration variables (from GitHub vars)
          DB_PORT=${{ vars.DB_PORT }}
          DB_NAME=${{ vars.DB_NAME }}
          NODE_ENV=${{ vars.NODE_ENV }}

          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG=${{ github.sha }}
          EOF

          # Print the contents of .env file
          echo "Contents of .env file:"
          cat .env

          # Deploy using Docker Compose with the remote context
          docker compose --env-file .env up -d

          # Clean up
          docker system prune -af --force
