name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-vps-deploy:latest, ${{ secrets.DOCKERHUB_USERNAME }}/docker-vps-deploy:${{ github.sha }}

  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Create Docker context
        run: |
          docker context create vps-context --docker "host=ssh://${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}"
          docker context use vps-context

      - name: Deploy to VPS with docker compose
        run: |
          # Create .env file from env.example and set values from secrets
          cp env.example .env

          # Use a different delimiter for sed to avoid issues with special characters
          sed -i "s|DB_USER=.*|DB_USER=${{ secrets.DB_USER }}|" .env
          sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" .env
          sed -i "s|DB_HOST=.*|DB_HOST=${{ secrets.DB_HOST }}|" .env
          sed -i "s|DB_PORT=.*|DB_PORT=${{ secrets.DB_PORT }}|" .env
          sed -i "s|DB_NAME=.*|DB_NAME=${{ secrets.DB_NAME }}|" .env
          sed -i "s|DB_URL=.*|DB_URL=${{ secrets.DB_URL }}|" .env

          # Add NODE_ENV to .env
          echo "NODE_ENV=production" >> .env

          # Print the contents of .env file
          echo "Contents of .env file:"
          cat .env

          # Deploy using Docker Compose with the remote context
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} \
          IMAGE_TAG=${{ github.sha }} \
          docker compose --env-file .env up -d

          # Clean up
          docker system prune -af --force
